config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # /admin/...
  namespace :admin do
    # GET /admin/dashboard
      resources :dashboard, only: [:index]
    end
    
    # GET /session/new
    resource :session, only: [:new, :create, :destroy]
    # GET /users/new
    get "/users/:id/edit_password", to: "users#edit_password", as: :edit_password
    patch "/users/:id/update_password", to: "users#update_password", as: :update_password
    resources :users, only: [:new, :create, :edit, :update, :show]
    # RESTful routes
    # /posts/:post_id/comments
    resources :posts do
      # get :my_route
      resources :comments, only: [:create, :destroy]
    end
  
    # Routes for PostsController
    #  get "/posts/new", to: "posts#new", as: :new_post
    #  post "/posts", to: "posts#create", as: :posts
    #  get "/posts/:id", to: "posts#show", as: :post
    #  get "/posts/:id/edit", to: "posts#edit", as: :edit_post
    #  patch "/posts/:id", to: "posts#update"
    #  delete "/posts/:id", to: "posts#destroy"
    get "/", to: "posts#index", as: :home
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <header id="header">
      <nav>
      <div class="nav-logo">
        <%= link_to posts_path do %>
          <div class="logo">LOGO</div>
        <% end %>
      </div>
        <div class="nav-links">
          <ul>
            <% if user_signed_in? %>
              <li><%= link_to 'New Post', new_post_path %></li>

              <% if current_user.present? %>
                <li class="nav-item title text-dark mr-4">Hi, <%= current_user.name %></li>
              <% else %>
                <li class="nav-item"><%= link_to('Sign Up', new_user_path) %></li>
                <li class="nav-item"><%= link_to('Sign Up', new_user_path) %></li>
              <% end %>
                <li class="nav-item">
                  <%= link_to session_path, method: :delete do %>
                    <div class="sign-out"></span>
                  <% end %>
                </li>

              <% else %>
                <li><%= link_to('Sign In', new_session_path) %></li>
                <li class="nav-item"><%= link_to('Sign Up', new_user_path) %></li>
            <% end %>
          </ul>
        </div>
      </nav>
    </header>

  <div class="container">
    <% flash.each do |type, message| %>
      <div class="alert alert-<%= type %> alert-dismissible fade show">
        <%= message %>
      </div>
    <% end %> 
    <%= yield %>
  </div>
  </body>
</html>